apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibGF1cmFkdWJhY2giLCJwYXNzd29yZCI6ImdocF9rbmh4OXpqWFZUcE5scTBzZXRBNmRRS25MWEpDRmkxZXcxSkQiLCJlbWFpbCI6ImxhdXJhLmR1YmFjaEBlZHUudGJ6LmNoIiwiYXV0aCI6ImJHRjFjbUZrZFdKaFkyZzZaMmh3WDJ0dWFIZzVlbXBZVmxSd1RteHhNSE5sZEVFMlpGRkxia3hZU2tOR2FURmxkekZLUkE9PSJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
  namespace: musicevents
type: kubernetes.io/dockerconfigjson
