apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: msvc-prod-db
  name: msvc-prod-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
