apiVersion: v1
kind: Service
metadata:
  name: {{ include "musiceventfinder.fullname" . }}-api
  labels:
    {{- include "musiceventfinder.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "musiceventfinder.api.selectorLabels" . | nindent 4 }}