apiVersion: v1
kind: Service
metadata:
  name: {{ include "musiceventfinder.fullname" . }}-db
  labels:
    {{- include "musiceventfinder.db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
      protocol: TCP
      name: mysql
  selector:
    {{- include "musiceventfinder.db.selectorLabels" . | nindent 4 }}