# ArgoCD Application für kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.0.0
    helm:
      releaseName: kube-prometheus-stack
      values: |
        # Minikube-optimierte Konfiguration
        
        # Prometheus Operator
        prometheusOperator:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        
        # Prometheus
        prometheus:
          prometheusSpec:
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: standard
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
            
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 1Gi
            
            # Service Discovery für Pods mit prometheus.io annotations
            additionalScrapeConfigs: []
          
          service:
            type: ClusterIP
          
          # Ingress für Prometheus
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              # nginx.ingress.kubernetes.io/auth-type: basic
              # nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
              # nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
            hosts:
              - prometheus.localhost
            paths:
              - /
            pathType: Prefix
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.localhost
        
        # Grafana
        grafana:
          enabled: true
          adminPassword: admin
          
          persistence:
            enabled: true
            storageClassName: standard
            size: 2Gi
          
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          
          service:
            type: ClusterIP
          
          # Ingress für Grafana
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              # nginx.ingress.kubernetes.io/ssl-redirect: "true"
            hosts:
              - grafana.localhost
            path: /
            pathType: Prefix
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.localhost
          
          # Standard Dashboards
          defaultDashboardsEnabled: true
          
          # Zusätzliche Datasources
          additionalDataSources: []
        
        # Alertmanager
        alertmanager:
          enabled: true
          
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: standard
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 1Gi
            
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
          
          service:
            type: ClusterIP
          
          # Ingress für Alertmanager
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              # nginx.ingress.kubernetes.io/auth-type: basic
              # nginx.ingress.kubernetes.io/auth-secret: alertmanager-basic-auth
              # nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
            hosts:
              - alertmanager.localhost
            paths:
              - /
            pathType: Prefix
            tls:
              - secretName: alertmanager-tls
                hosts:
                  - alertmanager.localhost
          
          config:
            global:
              resolve_timeout: 5m
            
            route:
              group_by: ['alertname', 'cluster', 'service']
              group_wait: 10s
              group_interval: 10s
              repeat_interval: 12h
              receiver: 'default'
              routes:
                - match:
                    alertname: Watchdog
                  receiver: 'null'
            
            receivers:
              - name: 'null'
              - name: 'default'
                # Hier kannst du deine Notifications konfigurieren
                # Beispiel für Slack:
                # slack_configs:
                # - api_url: 'YOUR_SLACK_WEBHOOK_URL'
                #   channel: '#alerts'
                #   title: '{{ .GroupLabels.alertname }}'
                #   text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        
        # Node Exporter
        nodeExporter:
          enabled: true
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
        
        # Kube State Metrics
        kube-state-metrics:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        # Prometheus Node Exporter
        prometheus-node-exporter:
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
        
        # Default Rules
        defaultRules:
          create: true
          rules:
            alertmanager: true
            etcd: true
            configReloaders: true
            general: true
            k8s: true
            kubeApiserverAvailability: true
            kubeApiserverSlos: true
            kubelet: true
            kubeProxy: true
            kubePrometheusGeneral: true
            kubePrometheusNodeRecording: true
            kubernetesApps: true
            kubernetesResources: true
            kubernetesStorage: true
            kubernetesSystem: true
            kubeScheduler: true
            kubeStateMetrics: true
            network: true
            node: true
            nodeExporterAlerting: true
            nodeExporterRecording: true
            prometheus: true
            prometheusOperator: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas